### ISSUE TITLE
Keep asking for fields

### ISSUE THREAD

**Issue by tienkhoi** [mitulgolakiya/laravel-api-generator#31] opened 2015-05-12 18:34 UTC
Hi,

Not sure if someone experience this issue.

I ran "php artisan mitul.generator:api Employee". The console asks for first field, I enter "name:string,255" and "required" for validation. The console asks for field again. At this point I want to finish my model so I left it blank and hit enter. But the console log doesn't let me enter. It keeps warning: "A value is required"
![image](https://cloud.githubusercontent.com/assets/7607653/7595261/ef95f042-f8b3-11e4-82b2-4edccede5b02.png)

**Comment by mitulgolakiya** [comment] 2015-05-15 04:16
@tienkhoi,
Are you still facing this issue? Can you describe some more details, like which version you are using of Laravel and Generator ? Also your local environment ?

**Comment by gayanhewa** [comment] 2015-05-24 10:33
This was fixed with the pull request I sent. Apparently this occurs  after an update to Laravel 5.1-dev branch. Probably caused by Symphony's console component's update.

**Comment by mitulgolakiya** [comment] 2015-06-12 05:57
It's fixed in new version and now rather then left it as a blank, we have to write exit to finish.

**Comment by tienkhoi** [comment] 2015-06-17 12:51
![image](https://cloud.githubusercontent.com/assets/7607653/8207232/e9a4db2c-14cd-11e5-9af7-0553abad5177.png)

Hi mitulgolakiya,

It still asks for a field. I typed exit but it didn't work. I'm using Laravel 5.1 with   "mitulgolakiya/laravel-api-generator": "1.3.*"

**Comment by mitulgolakiya** [comment] 2015-06-17 18:35
For laravel 5.1, you should use [master](https://github.com/mitulgolakiya/laravel-api-generator/tree/master) branch. This issue is fixed in master branch.

**Closed as completed** 2015-07-02 05:27 UTC
Labels: bug, ready
