### ISSUE TITLE
is generator support reference field type?

### ISSUE THREAD

**Issue by jiqimaogou** [mitulgolakiya/laravel-api-generator#102] opened 2015-09-07 05:24 UTC
if I have a model reference another model, can generator support?

**Comment by gayanhewa** [comment] 2015-09-07 08:45
Relationships ?

**Comment by jiqimaogou** [comment] 2015-09-08 01:39
one to one, on two many, and many to many api generator?

**Comment by gayanhewa** [comment] 2015-09-08 02:51
@mitulgolakiya I don't think we support this atm moment.

**Comment by mitulgolakiya** [comment] 2015-09-08 03:13
Yes, it's in roadmap.

**Comment by mitulgolakiya** [comment] 2015-09-08 03:14
Duplicate of https://github.com/mitulgolakiya/laravel-api-generator/issues/92

**Closed as completed** 2015-09-08 03:14 UTC
