### ISSUE TITLE
where do i create the app.blade.php

### ISSUE THREAD

**Issue by jiqimaogou** [mitulgolakiya/laravel-api-generator#97] opened 2015-09-02 01:45 UTC
hello, I'm new to php, and I create a scaffold_api, and open the /xxxxs, it said view app not found, and i create the app.blade.php in the same directory(resources/views/xxx/) it doesn't work. where should i create the file?

**Comment by mitulgolakiya** [comment] 2015-09-02 03:39
@jiqimaogou if you have `resources/views/xxx/` then you should use `xxx.app`. Or it should be in the main root folder of views (`resources/views/`).

If you want to use it in sub folder then you can [publish](https://github.com/mitulgolakiya/laravel-api-generator#customize-templates) templates and modify them to use it in `resources/views/xxx/` folder.

**Comment by jiqimaogou** [comment] 2015-09-02 05:05
can you generate the default app.blade.php?

**Comment by mitulgolakiya** [comment] 2015-09-02 05:19
Its already in queue. :)
Duplicate of https://github.com/mitulgolakiya/laravel-api-generator/issues/83

**Closed as completed** 2015-09-02 05:20 UTC
Labels: help wanted
