### ISSUE TITLE
More fields type

### ISSUE THREAD

**Issue by butoibogdan** [mitulgolakiya/laravel-api-generator#80] opened 2015-07-19 08:16 UTC
Could you help me to use more fields type in view form templates from Laravel 5.0. If is possible how can i use this to customize my application.
Thank you very much

**Comment by mitulgolakiya** [comment] 2015-07-20 04:13
@butoibogdan,
as of now, customized template is not supported. It's in a roadmap. I will let you know once its done.

**Comment by mitulgolakiya** [comment] 2015-07-20 04:16
duplicate of #67.

**Closed as completed by mitulgolakiya** 2015-07-20 04:16 UTC
Labels: enhancement
